# Welcome to Jekyll!
#

# Site settings
title: 参照物
description: |
  简单博客
owner: zhangwentao
first_published: 2019 # if migrating another site, the year of your first publish
email: go.secret@163.com
baseurl: ""
port: 4001
url: "http://reference.fun"
social:
  github: https://github.com/daai
# Build settings
markdown: kramdown
#sass:
#  style: compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
      author: "Mr. zhang"
paginate: 5
paginate_path: "blog/page:num"

plugins:
  - jekyll-paginate

links1:
  - name:         博客列表
    url:          /blog
    type:         blogs
    external:     false
  - name:         关于
    url:          /about
    type:         about
    external:     false

blog_1:    blogs
blog_2:    about